name: Helm Check
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'wso2/apk'
          ref: 'main'

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: helm-charts/
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
