name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 21 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'Stale issue message'
          stale-issue-label: 'stale'
          days-before-issue-stale: 1
          days-before-issue-close: 1
